# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "91acbcade75e532802e562963a1b35ec"
name = "shipping-service"
handle = "shipping-service-4"
application_url = "https://heroes-reserves-roller-settled.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-dcf9ec17.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://heroes-reserves-roller-settled.trycloudflare.com/auth/callback",
  "https://heroes-reserves-roller-settled.trycloudflare.com/auth/shopify/callback",
  "https://heroes-reserves-roller-settled.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
